apiVersion: v1
kind: Service
metadata:
  name: postgres-###APP_NAME###
  labels:
    app: ###APP_NAME###
    tier: postgres
spec:
  selector:
    app: ###APP_NAME###
    tier: postgres
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
