apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ###NAMESPACE###
  name: postgres-config
  labels:
    app: ###APP_NAME###
    tier: postgres
data:
  POSTGRES_DB: ###DB_NAME###
  POSTGRES_USER: ###DB_USER###
  POSTGRES_PASSWORD: ###DB_PASS###
  PGDATA: /var/lib/postgresql/data/pgdata
